# Generated by Django 4.1.13 on 2024-07-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('job_id', models.IntegerField(null=True)),
                ('wv_uuid', models.CharField(max_length=37, primary_key=True, serialize=False)),
                ('company_name', models.TextField(null=True)),
                ('company_id', models.IntegerField(null=True)),
                ('title', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
                ('annotations', models.TextField(null=True)),
                ('vector', models.TextField(null=True)),
                ('entity_indices', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('products', models.TextField()),
                ('vector', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QueryEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('rag_query', models.TextField(null=True)),
                ('query_embedding', models.TextField()),
                ('rag_query_embedding', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubComponemtEmbeddings',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('embedding', models.BinaryField(null=True)),
                ('text', models.TextField(null=True)),
                ('entity', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('querys', models.TextField(null=True)),
                ('summaries', models.TextField(null=True)),
            ],
        ),
    ]
