# Generated by Django 5.0.6 on 2024-06-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('products', models.TextField()),
                ('vector', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QueryEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('rag_query', models.TextField(null=True)),
                ('query_embedding', models.TextField()),
                ('rag_query_embedding', models.TextField(null=True)),
            ],
        ),
    ]
