# Generated by Django 4.1.13 on 2024-07-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_summaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(null=True)),
                ('wv_uuid', models.TextField(null=True)),
                ('company_name', models.TextField(null=True)),
                ('company_id', models.UUIDField(null=True)),
                ('title', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
                ('annotaions', models.TextField(null=True)),
                ('vector', models.TextField(null=True)),
            ],
        ),
    ]
