# Generated by Django 4.1.13 on 2024-07-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_annotaions_joblisting_annotations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubComponemtEmbeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('embedding', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
                ('entity', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='joblisting',
            name='entity_indices',
            field=models.TextField(null=True),
        ),
    ]
