# Generated by Django 4.1.13 on 2024-07-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subcomponemtembeddings_joblisting_entity_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcomponemtembeddings',
            name='embedding',
            field=models.BinaryField(null=True),
        ),
    ]
